# Ejercicio 1

In [1]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

x_min = data.min()
x_max = data.max()

normalized = (data - x_min) / (x_max - x_min)

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


# Ejercicio 2

In [2]:
import numpy as np

data = np.array([2, 4, 4, 4, 5, 5, 7, 9])

mean = data.mean()
std = data.std()

z_scores = (data - mean) / std

print(mean)
print(std)
print(z_scores)

# Verificación
print("Media estandarizada:", z_scores.mean())
print("Std estandarizada:", z_scores.std())

5.0
2.0
[-1.5 -0.5 -0.5 -0.5  0.   0.   1.   2. ]
Media estandarizada: 0.0
Std estandarizada: 1.0


# Ejercicio 3

In [7]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

datos = np.array([100, 200, 300, 400, 500]).reshape(-1, 1)

# MinMaxScaler
minmax = MinMaxScaler()
datos_minmax = minmax.fit_transform(datos)

print("\nMin-Max Scaling:")
print(datos_minmax)

# StandardScaler
standard = StandardScaler()
datos_standard = standard.fit_transform(datos)

print("\nStandard Scaling (Z-score):")
print(datos_standard)

# Comparación
print("\n--- Comparación ---")
for i in range(len(datos)):
    print(f"Original: {datos[i]} | MinMax: {datos_minmax[i]} | Z-score: {datos_standard[i]}")



Min-Max Scaling:
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]

Standard Scaling (Z-score):
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]

--- Comparación ---
Original: [100] | MinMax: [0.] | Z-score: [-1.41421356]
Original: [200] | MinMax: [0.25] | Z-score: [-0.70710678]
Original: [300] | MinMax: [0.5] | Z-score: [0.]
Original: [400] | MinMax: [0.75] | Z-score: [0.70710678]
Original: [500] | MinMax: [1.] | Z-score: [1.41421356]


# Ejercicio 4

In [11]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, np.nan],
    'C': [1, 2, 3, 4, 5]
})

print("\n" + str(df.isnull()))

print("\n" + str(df.isnull().sum()))

porcentaje = df.isnull().mean() * 100
print("\n" + str(porcentaje))

print("\n" + str(df[df.isnull().any(axis=1)]))


       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False  False
4  False   True  False

A    1
B    2
C    0
dtype: int64

A    20.0
B    40.0
C     0.0
dtype: float64

     A    B  C
0  1.0  NaN  1
2  NaN  3.0  3
4  5.0  NaN  5


# Ejercicio 5

In [14]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, np.nan],
    'C': [1, 2, 3, 4, 5]
})

display(df)

display(df.dropna())

display(df.dropna(axis=1))

display(df.fillna(df.mean()))

display(df.fillna(df.median()))

display(df.ffill())

display(df.bfill())

,A,B,C
0,1.0,NaN,1
1,2.0,2.0,2
2,NaN,3.0,3
3,4.0,4.0,4
4,5.0,NaN,5


,A,B,C
1,2.0,2.0,2
3,4.0,4.0,4


,C
0,1
1,2
2,3
3,4
4,5


,A,B,C
0,1.0,3.0,1
1,2.0,2.0,2
2,3.0,3.0,3
3,4.0,4.0,4
4,5.0,3.0,5


,A,B,C
0,1.0,3.0,1
1,2.0,2.0,2
2,3.0,3.0,3
3,4.0,4.0,4
4,5.0,3.0,5


,A,B,C
0,1.0,NaN,1
1,2.0,2.0,2
2,2.0,3.0,3
3,4.0,4.0,4
4,5.0,4.0,5


,A,B,C
0,1.0,2.0,1
1,2.0,2.0,2
2,4.0,3.0,3
3,4.0,4.0,4
4,5.0,NaN,5


# Ejercicio 6

In [16]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, np.nan],
    'C': [1, 2, 3, 4, 5]
})

display(df)

imputer_mean = SimpleImputer(strategy='mean')
df_mean = pd.DataFrame(imputer_mean.fit_transform(df), columns=df.columns)

display(df_mean)

imputer_median = SimpleImputer(strategy='median')
df_median = pd.DataFrame(imputer_median.fit_transform(df), columns=df.columns)

display(df_median)

imputer_freq = SimpleImputer(strategy='most_frequent')
df_freq = pd.DataFrame(imputer_freq.fit_transform(df), columns=df.columns)

display(df_freq)

imputer_const = SimpleImputer(strategy='constant', fill_value=0)
df_const = pd.DataFrame(imputer_const.fit_transform(df), columns=df.columns)

display(df_const)

,A,B,C
0,1.0,NaN,1
1,2.0,2.0,2
2,NaN,3.0,3
3,4.0,4.0,4
4,5.0,NaN,5


,A,B,C
0,1.0,3.0,1.0
1,2.0,2.0,2.0
2,3.0,3.0,3.0
3,4.0,4.0,4.0
4,5.0,3.0,5.0


,A,B,C
0,1.0,3.0,1.0
1,2.0,2.0,2.0
2,3.0,3.0,3.0
3,4.0,4.0,4.0
4,5.0,3.0,5.0


,A,B,C
0,1.0,2.0,1.0
1,2.0,2.0,2.0
2,1.0,3.0,3.0
3,4.0,4.0,4.0
4,5.0,2.0,5.0


,A,B,C
0,1.0,0.0,1.0
1,2.0,2.0,2.0
2,0.0,3.0,3.0
3,4.0,4.0,4.0
4,5.0,0.0,5.0


# Ejercicio 7

In [17]:
import numpy as np

datos = np.array([10, 12, 14, 15, 16, 18, 20, 22, 25, 100])

Q1 = np.percentile(datos, 25)
Q3 = np.percentile(datos, 75)
IQR = Q3 - Q1

lim_inf = Q1 - 1.5 * IQR
lim_sup = Q3 + 1.5 * IQR

outliers = datos[(datos < lim_inf) | (datos > lim_sup)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Límites:", lim_inf, lim_sup)
print("Outliers:", outliers)

Q1: 14.25
Q3: 21.5
IQR: 7.25
Límites: 3.375 32.375
Outliers: [100]


# Ejercicio 8

In [18]:
from scipy import stats
import numpy as np

datos = np.array([10, 12, 14, 15, 16, 18, 20, 22, 25, 100])

z_scores = stats.zscore(datos)

outliers = np.where(np.abs(z_scores) > 3)

print("Z-scores:", z_scores)
print("Outliers (índices):", outliers)
print("Valores atípicos:", datos[outliers])

Z-scores: [-0.60066384 -0.52162913 -0.44259441 -0.40307705 -0.36355969 -0.28452498
 -0.20549026 -0.12645555 -0.00790347  2.95589838]
Outliers (índices): (array([], dtype=int64),)
Valores atípicos: []


# Ejercicio 9

In [19]:
from scipy.stats import boxcox
datos_sin_outliers = datos[(datos >= lim_inf) & (datos <= lim_sup)]

print("\n--- Sin Outliers ---")
print(datos_sin_outliers)

datos_capped = np.clip(datos, lim_inf, lim_sup)

print("\n--- Capping ---")
print(datos_capped)

datos_log = np.log(datos)

print("\n--- Transformación Logarítmica ---")
print(datos_log)

datos_boxcox, lambda_ = boxcox(datos)

print("\n--- Transformación Box-Cox ---")
print("Lambda:", lambda_)
print(datos_boxcox)


--- Sin Outliers ---
[10 12 14 15 16 18 20 22 25]

--- Capping ---
[10.    12.    14.    15.    16.    18.    20.    22.    25.    32.375]

--- Transformación Logarítmica ---
[2.30258509 2.48490665 2.63905733 2.7080502  2.77258872 2.89037176
 2.99573227 3.09104245 3.21887582 4.60517019]

--- Transformación Box-Cox ---
Lambda: -1.098070951659969
[0.83802742 0.85121056 0.86047224 0.86413601 0.86732086 0.87258214
 0.87674527 0.88011805 0.88412159 0.90489064]


# Ejercicio 10

In [20]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

df = pd.DataFrame({
    'color': ['rojo', 'azul', 'verde', 'rojo', 'verde'],
    'talla': ['S', 'M', 'L', 'S', 'M']
})

display(df)

le_color = LabelEncoder()
le_talla = LabelEncoder()

df['color_label'] = le_color.fit_transform(df['color'])
df['talla_label'] = le_talla.fit_transform(df['talla'])

display(df)

df_dummies = pd.get_dummies(df[['color', 'talla']])
print("\nOne-Hot Encoding con get_dummies:")
display(df_dummies)

ohe = OneHotEncoder(sparse_output=False)
encoded = ohe.fit_transform(df[['color', 'talla']])
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out())

print("\nOne-Hot Encoding con sklearn:")
display(encoded_df)

,color,talla
0,rojo,S
1,azul,M
2,verde,L
3,rojo,S
4,verde,M


,color,talla,color_label,talla_label
0,rojo,S,1,2
1,azul,M,0,1
2,verde,L,2,0
3,rojo,S,1,2
4,verde,M,2,1



One-Hot Encoding con get_dummies:


,color_azul,color_rojo,color_verde,talla_L,talla_M,talla_S
0,False,True,False,False,False,True
1,True,False,False,False,True,False
2,False,False,True,True,False,False
3,False,True,False,False,False,True
4,False,False,True,False,True,False



One-Hot Encoding con sklearn:


,color_azul,color_rojo,color_verde,talla_L,talla_M,talla_S
0,0.0,1.0,0.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,1.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,1.0
4,0.0,0.0,1.0,0.0,1.0,0.0


# Ejercicio 11

In [21]:
import numpy as np
import pandas as pd
from scipy import stats

datos = np.array([1, 2, 3, 4, 5, 10, 20, 30])

log = np.log(datos)
print("Logaritmo natural:")
display(log)

sqrt = np.sqrt(datos)
print("\nRaíz cuadrada:")
display(sqrt)

boxcox = stats.boxcox(datos)
print("\nTransformación Box-Cox:")
display(boxcox)

bins = pd.cut(datos, bins=3, labels=['Bajo', 'Medio', 'Alto'])
print("\nDiscretización:")
display(bins)

Logaritmo natural:


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       2.30258509, 2.99573227, 3.40119738])


Raíz cuadrada:


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       3.16227766, 4.47213595, 5.47722558])


Transformación Box-Cox:


(array([0.        , 0.67408126, 1.05123102, 1.31142272, 1.50911612,
        2.10094523, 2.66051756, 2.97359935]),
 np.float64(-0.08085602060685483))


Discretización:


['Bajo', 'Bajo', 'Bajo', 'Bajo', 'Bajo', 'Bajo', 'Medio', 'Alto']
Categories (3, str): ['Bajo' < 'Medio' < 'Alto']

# Ejercicio 12

In [23]:
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures

df_fe = pd.DataFrame({
    'ventas': [100, 200, 150, 300, 250],
    'costos': [50, 120, 100, 200, 180],
    'fecha': pd.date_range(start='2024-01-01', periods=5)
})

print("DataFrame original:")
display(df_fe)

df_fe['ratio'] = df_fe['ventas'] / df_fe['costos']

df_fe['ganancia'] = df_fe['ventas'] - df_fe['costos']

df_fe['ventas_altas'] = (df_fe['ventas'] > 200).astype(int)

poly = PolynomialFeatures(degree=2, include_bias=False)
poly_feat = poly.fit_transform(df_fe[['ventas', 'costos']])
poly_df = pd.DataFrame(poly_feat, columns=poly.get_feature_names_out())

print("\nPolynomial Features:")
display(poly_df)

df_fe['año'] = df_fe['fecha'].dt.year
df_fe['mes'] = df_fe['fecha'].dt.month
df_fe['dia'] = df_fe['fecha'].dt.day

print("\nFeature Engineering final:")
display(df_fe)

DataFrame original:


,ventas,costos,fecha
0,100,50,2024-01-01
1,200,120,2024-01-02
2,150,100,2024-01-03
3,300,200,2024-01-04
4,250,180,2024-01-05



Polynomial Features:


,ventas,costos,ventas^2,ventas costos,costos^2
0,100.0,50.0,10000.0,5000.0,2500.0
1,200.0,120.0,40000.0,24000.0,14400.0
2,150.0,100.0,22500.0,15000.0,10000.0
3,300.0,200.0,90000.0,60000.0,40000.0
4,250.0,180.0,62500.0,45000.0,32400.0



Feature Engineering final:


,ventas,costos,fecha,ratio,ganancia,ventas_altas,año,mes,dia
0,100,50,2024-01-01,2.000000,50,0,2024,1,1
1,200,120,2024-01-02,1.666667,80,0,2024,1,2
2,150,100,2024-01-03,1.500000,50,0,2024,1,3
3,300,200,2024-01-04,1.500000,100,1,2024,1,4
4,250,180,2024-01-05,1.388889,70,1,2024,1,5


# Ejercicio 13

In [25]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, MaxAbsScaler
import numpy as np
import pandas as pd

data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

df = pd.DataFrame(data, columns=['A', 'B', 'C'])

# Escaladores
minmax = MinMaxScaler()
standard = StandardScaler()
robust = RobustScaler()
maxabs = MaxAbsScaler()

# transformaciones
df_minmax = pd.DataFrame(minmax.fit_transform(df), columns=df.columns)
df_standard = pd.DataFrame(standard.fit_transform(df), columns=df.columns)
df_robust = pd.DataFrame(robust.fit_transform(df), columns=df.columns)
df_maxabs = pd.DataFrame(maxabs.fit_transform(df), columns=df.columns)

# Mostrar resultados
display(("Original:", df))
display("MinMaxScaler:", df_minmax)
display("StandardScaler:", df_standard)
display("RobustScaler:\n", df_robust)
display("MaxAbsScaler:\n", df_maxabs)

('Original:',
     A   B   C
 0   1   2   3
 1   4   5   6
 2   7   8   9
 3  10  11  12)

'MinMaxScaler:'

,A,B,C
0,0.000000,0.000000,0.000000
1,0.333333,0.333333,0.333333
2,0.666667,0.666667,0.666667
3,1.000000,1.000000,1.000000


'StandardScaler:'

,A,B,C
0,-1.341641,-1.341641,-1.341641
1,-0.447214,-0.447214,-0.447214
2,0.447214,0.447214,0.447214
3,1.341641,1.341641,1.341641


'RobustScaler:\n'

,A,B,C
0,-1.000000,-1.000000,-1.000000
1,-0.333333,-0.333333,-0.333333
2,0.333333,0.333333,0.333333
3,1.000000,1.000000,1.000000


'MaxAbsScaler:\n'

,A,B,C
0,0.1,0.181818,0.25
1,0.4,0.454545,0.50
2,0.7,0.727273,0.75
3,1.0,1.000000,1.00


# Ejercicio 14

In [27]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

# Datos
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

df = pd.DataFrame(data, columns=['A', 'B', 'C'])


numericas = ['A', 'B', 'C']


transformador = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numericas)
    ]
)

pipeline = Pipeline(steps=[
    ('preprocesamiento', transformador)
])

resultado = pipeline.fit_transform(df)

df_final = pd.DataFrame(resultado, columns=numericas)

display(("Datos originales:", df))
display(("Datos escalados:", df_final))

('Datos originales:',
     A   B   C
 0   1   2   3
 1   4   5   6
 2   7   8   9
 3  10  11  12)

('Datos escalados:',
           A         B         C
 0 -1.341641 -1.341641 -1.341641
 1 -0.447214 -0.447214 -0.447214
 2  0.447214  0.447214  0.447214
 3  1.341641  1.341641  1.341641)

# Ejercicio 15: Mejores Prácticas

### ¿Por qué es importante la preparación de datos?
Porque mejora la calidad del modelo. Datos limpios y bien transformados → mejores predicciones.

---

### ¿Qué es data leakage?
Es cuando el modelo usa información que no debería (como datos de prueba).

**Cómo evitarlo:**
- Separar train/test antes de procesar
- No usar datos de prueba en el entrenamiento

---

### Diferencia entre entrenamiento y prueba
- **Train:** para entrenar el modelo  
- **Test:** para evaluar su rendimiento  

---

# Ejercicio 16: Técnicas Avanzadas

### ¿Qué es SMOTE?
Técnica para balancear datos generando ejemplos sintéticos de la clase minoritaria.

---

### ¿Qué es imputación KNN?
Rellena valores faltantes usando los datos más similares (vecinos cercanos).

---

### ¿Qué es Target Encoding?
Convierte categorías en el promedio del valor objetivo.

**Riesgo:** puede causar data leakage si se usa mal