# Procesamiento de Datos en Python

**Entorno:** `myenv` (numpy, pandas, ipykernel)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 1. map y filter

In [10]:
# map(): Duplicar numeros usando funcion y lambda
def duplicar(x):
    return x * 2

numeros = [1, 2, 3, 4, 5]

resultado_funcion = map(duplicar, numeros)
print(list(resultado_funcion))
#------------------
resultado_lambda = map(lambda x: x * 2, numeros)
print(list(resultado_lambda))
# Completar con map(duplicar, numeros) y map(lambda x: x*2, numeros)

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]


In [18]:
# filter(): Obtener numeros pares e impares

def es_par(i):
    return i % 2 == 0

def es_impar(i):
    return i % 2 != 0

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

pares = filter(es_par, numeros)
impares = filter(es_impar, numeros)

print(list(pares))
print(list(impares))
# Completar con filter para obtener pares e impares

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]


In [56]:
# Combinar map y filter: Celsius a Fahrenheit y filtrar > 80
celsius = [10, 18, 25, 30, 15, 35, 40]

temp_farenheit = list(map(lambda x: (x * 9/5) + 32, celsius))
print(list(temp_farenheit))

# Completar: map para convertir a F, filter para > 80

fitrar_fah = list(filter(lambda i: i > 80, temp_farenheit))
print(list(fitrar_fah))

[50.0, 64.4, 77.0, 86.0, 59.0, 95.0, 104.0]
[86.0, 95.0, 104.0]


## 2. Lambda

In [ ]:
# Lambda basicas: cuadrado, suma, maximo
# Completar: cuadrado = lambda ... ; suma = lambda ... ; maximo = lambda ...
cuadrado = lambda x: x ** 2
suma = lambda a, b: a + b
maximo = lambda a, b: a if a > b else b

print(cuadrado(5))
print(suma(5, 4))
print(maximo(10, 20))  

25
7
20


In [9]:
# sorted() con lambda: ordenar por edad y por nombre (desc)
personas = [("Ana", 25), ("Carlos", 30), ("Beatriz", 22)]

sorteo = sorted(personas, key=lambda x: x[1])
print(sorteo)

sorteo_p = sorted(personas, key=lambda x: x[0])
print(sorteo_p)
# Completar: sorted(personas, key=...)

[('Beatriz', 22), ('Ana', 25), ('Carlos', 30)]
[('Ana', 25), ('Beatriz', 22), ('Carlos', 30)]


In [18]:
# max() y min() con lambda: mayor y menor edad
personas = [{"nombre": "Ana", "edad": 25}, {"nombre": "Carlos", "edad": 30}]

mayor = max(personas, key=lambda x: x["edad"])
menor = min(personas, key=lambda x: x["edad"])

print(mayor)
print(menor)
# Completar: max(..., key=...), min(..., key=...)

{'nombre': 'Carlos', 'edad': 30}
{'nombre': 'Ana', 'edad': 25}


## 3. NumPy

In [27]:
# Sin NumPy: suma con bucle for
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]

suma = []
for i in range(len(a)):
    suma.append(a[i] + b[i])
print(suma)


# Completar: bucle for para sumar elementos

[11, 22, 33, 44, 55]


In [37]:

import numpy as np
# Con NumPy: operaciones +, -, *, /
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a + b)
print(a - b)
print(a * b)
print(b / a)

# Completar: a+b, a-b, a*b, b/a

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [40]:
# Funciones NumPy: sqrt, mean, std, median
a = np.array([1, 2, 3, 4, 5])

print(np.sqrt(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))
# Completar: np.sqrt(a), np.mean(a), np.std(a), np.median(a)

[1.         1.41421356 1.73205081 2.         2.23606798]
3.0
1.4142135623730951
3.0


## 4. Limpieza de Datos

In [86]:
import pandas as pd
# Crear DataFrame con valores nulos
data = {'nombre': ['Juan', 'Maria', None, 'Ana'], 'edad': [25, None, 30,40], 'salario': [50000, None, 48000, 12000]}
df = pd.DataFrame(data)
display(df)
print(df.info())
print(df.isnull().sum())

,nombre,edad,salario
0,Juan,25.0,50000.0
1,Maria,NaN,NaN
2,NaN,30.0,48000.0
3,Ana,40.0,12000.0


<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   nombre   3 non-null      str    
 1   edad     3 non-null      float64
 2   salario  3 non-null      float64
dtypes: float64(2), str(1)
memory usage: 228.0 bytes
None
nombre     1
edad       1
salario    1
dtype: int64


In [87]:
# Deteccion de nulos: isnull().sum()
# Completar: df.isnull().sum()



In [88]:
# Estrategias: dropna() y fillna()
# Completar: df.dropna() y df.fillna(valor)

In [89]:
# Correccion de tipos: pd.to_numeric(..., errors='coerce')
df = pd.DataFrame({'edad': [25, 'desconocida', 30]})
# Completar: convertir columna edad a numerico

## 5. Reindexacion

In [90]:
# reindex() con fill_value
serie = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
# Completar: serie.reindex(['a','b','c','d'], fill_value=0)

In [91]:
# reindex en DataFrame: filas y columnas
df = pd.DataFrame({'col1': [1,2,3], 'col2': [4,5,6]}, index=['x','y','z'])
# Completar: df.reindex(['x','y','z','w']) y df.reindex(columns=[...], fill_value=0)

In [92]:
# ffill() y bfill()
serie = pd.Series([100, None, 300, None, 500])
# Completar: serie.ffill() y serie.bfill()

## 6. apply()

In [93]:
# apply() basic: suma por columna
df = pd.DataFrame({'a': [1,2,3], 'b': [4,5,6], 'c': [7, 8, 9]})
# Completar: df.apply(sum)

In [94]:
# apply() con axis: axis=0 (columnas), axis=1 (filas)
# Completar: df.apply(max, axis=0) y df.apply(sum, axis=1)

In [95]:
# apply() con columnas: calcular IMC
df = pd.DataFrame({'peso': [70, 65], 'altura': [1.70, 1.60]})
# Completar: def imc(fila): return... ; df['imc'] = df.apply(..., axis=1)

In [96]:
# apply() para clasificacion (ej: IMC normal/sobrepeso)
df['categoria'] = df['imc'].apply(lambda x: 'Normal' if x < 25 else 'Sobrepeso')
# Completar: funcion con if/elif/else

KeyError: 'imc'

## 7. Merges

In [ ]:
# DataFrames para merge
# DataFrame de empleados
empleados = pd.DataFrame({'id_empleado': [1, 2, 3, 4],'nombre': ['Juan', 'Maria', 'Pedro', 'Ana'],'departamento_id': [10, 20, 10, 30]})

# DataFrame de departamentos
departamentos = pd.DataFrame({'departamento_id': [10, 20, 30], 'nombre_dept': ['TI', 'Ventas', 'RH']})

In [ ]:
# INNER JOIN: solo claves en ambas tablas
# Completar: pd.merge(empleados, departamentos, on='dept_id', how='inner')

In [ ]:
# LEFT JOIN: todos de empleados
# Completar: how='left'

In [ ]:
# RIGHT JOIN: todos de departamentos
# Completar: how='right'

In [ ]:
# OUTER JOIN: todos de ambas
# Completar: how='outer'

In [ ]:
# Merge con claves diferentes: left_on, right_on
df1 = pd.DataFrame({'id': [1,2], 'nombre': ['Juan','Maria']})
df2 = pd.DataFrame({'emp_id': [1,3], 'salario': [50000,60000]})
# Completar: pd.merge(df1, df2, left_on='id', right_on='emp_id', how='inner')

In [ ]:
# Merge multiple: encadenar merge()
# Completar: df1.merge(df2, on='...').merge(df3, on='...')

---
## Ejercicios

In [ ]:
# 1. temps = [15,22,30,18,25] -> Fahrenheit y filtrar >20

In [ ]:
# 2. personas = [{'nombre':'Ana','edad':25},{'nombre':'Carlos','edad':30}] -> ordenar por edad, max

In [ ]:
# 3. NumPy: a=np.array([1,2,3,4,5]), b=np.array([10,20,30,40,50]) -> +,-,*,/ y media,std

In [ ]:
# 4. df con nulos -> dropna, fillna, ffill

In [ ]:
# 5. serie.reindex(['a','b','c','d'], fill_value=0), ffill, bfill

In [ ]:
# 6. df(precio,cantidad) -> apply(lambda x: x['precio']*x['cantidad'], axis=1)

In [ ]:
# 7. df1,df2 -> inner, left, right, outer